Update workflow file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,10 +29,15 @@ jobs:
             ls && \
             if [ -f package.json ]; then \
               echo 'Running backup...' && \
-              npm run backup || echo 'Backup failed, continuing anyway'; \
-              nvm use || true; \
-            fi \
-            npm i || true && \
-            pm2 delete w8-tracker || true && \
-            pm2 save --force && \
-            pm2 start ./server/application.ts --interpreter=node --node-args='--env-file=./configurations/.env' --watch --name=w8-tracker"
+              npm run backup || echo 'Backup failed, continuing anyway' && \
+              nvm use || true \
+              npm i || true && \
+              pm2 delete w8-tracker || true && \
+              pm2 save --force && \
+              pm2 start ./server/application.ts --interpreter=node --node-args='--env-file=./configurations/.env' --watch --name=w8-tracker"
+            else
+              npm i || true && \
+              pm2 delete w8-tracker || true && \
+              pm2 save --force && \
+              pm2 start ./server/application.ts --interpreter=node --node-args='--env-file=./configurations/.env' --watch --name=w8-tracker"
+            fi"
